export const CURRENCY = process.env.NEXT_PUBLIC_CURRENCY || 'SOL';
export const MAX_VALUE = Number(process.env.NEXT_PUBLIC_MAX_VALUE) || 99999.99;
export const IS_CUSTOMER_POS = process.env.NEXT_PUBLIC_IS_CUSTOMER_POS === 'true' || false;
export const POS_USE_WALLET = process.env.NEXT_PUBLIC_POS_USE_WALLET === 'true' || false;
export const SHOW_SYMBOL = process.env.NEXT_PUBLIC_SHOW_SYMBOL === 'true' || false;
export const SHOW_MERCHANT_LIST = process.env.NEXT_PUBLIC_SHOW_MERCHANT_LIST === 'true' || false;
export const IS_DEV = process.env.NEXT_PUBLIC_IS_DEV === 'true' || false;
export const USE_HTTP = process.env.NEXT_PUBLIC_USE_HTTP === 'true' || false;
export const USE_LINK = process.env.NEXT_PUBLIC_USE_LINK === 'true' || false;
export const USE_WEB_WALLET = process.env.NEXT_PUBLIC_USE_WEB_WALLET === 'true' || false;
export const AUTO_CONNECT = process.env.NEXT_PUBLIC_AUTO_CONNECT === 'true' || false;
export const USE_CUSTOM_CRYPTO = process.env.NEXT_PUBLIC_USE_CUSTOM_CRYPTO === 'true' || false;
export const DEFAULT_WALLET = process.env.NEXT_PUBLIC_DEFAULT_WALLET;
export const APP_TITLE = process.env.NEXT_PUBLIC_APP_TITLE || 'FiMs Pay';
export const DEFAULT_LANGUAGE = process.env.NEXT_PUBLIC_DEFAULT_LANGUAGE || 'en';
export const DEFAULT_THEME = process.env.NEXT_PUBLIC_DEFAULT_THEME || 'classic';
export const MERCHANT_IMAGE_PATH = process.env.NEXT_PUBLIC_MERCHANT_IMAGE_PATH || '/Img/Merchant/';
export const FAUCET_LINK = (!IS_DEV ? process.env.NEXT_PUBLIC_FAUCET_LINK : null) || 'https://spl-token-faucet.com';
export const ABOUT = process.env.NEXT_PUBLIC_ABOUT || 'https://fims.fi/';
export const FAUCET_ADDRESS = process.env.NEXT_PUBLIC_FAUCET_ADDRESS;
export const FAUCET_SUPPLY_AMOUNT = process.env.FAUCET_SUPPLY_AMOUNT || 1;
export const GOOGLE_SPREADSHEET_ID = process.env.NEXT_PUBLIC_GOOGLE_SPREADSHEET_ID;
export const GOOGLE_API_KEY = process.env.NEXT_PUBLIC_GOOGLE_API_KEY;
export const CRYPTO_SECRET = process.env.NEXT_PUBLIC_CRYPTO_SECRET || APP_TITLE;
export const FAUCET_ENCODED_KEY = IS_DEV ? process.env.NEXT_PUBLIC_FAUCET_ENCODED_KEY : null;
